apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8suniqueingresshost
  annotations:
    description: >-
      Requires all Ingress rule hosts to be unique.

      Does not handle hostname wildcards:
      https://kubernetes.io/docs/concepts/services-networking/ingress/
spec:
  crd:
    spec:
      names:
        kind: K8sUniqueIngressHost
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8suniqueingresshost

        deny[msg] {
            is_ingress
            input_host := input.request.object.spec.rules[_].host
            some other_ns, other_name
            other_host := data.kubernetes.ingresses[other_ns][other_name].spec.rules[_].host
            [input_ns, input_name] != [other_ns, other_name]

            input_host == other_host

            msg := sprintf("Ingress host conflicts with ingress %v/%v", [other_ns, other_name])
        }

        input_ns = input.request.object.metadata.namespace

        input_name = input.request.object.metadata.name

        is_ingress {
            input.request.kind.kind == "Ingress"
            input.request.kind.group == "networking.k8s.io"
            input.request.kind.version == "v1"
        }
